draw_set_color(c_black)
draw_set_font(fnt_GUI)
draw_text(420, 120, "TUTORIAL")
draw_set_font(fnt_GUI_sm)
draw_text(50, 180, "~ WASD to move")
draw_text(50, 280, "~ Collect fire extinguishers to help Ferdinand escape the fire")
draw_text(50, 380, "~ Watch out for layered fire")
draw_text(50, 480, "~ Every 10 seconds you do not have a fire exnguisher a new one will spawn")
draw_text(250, 580, "(press ENTER to return to the main menu)")